#  pytorch 学习笔记

In [19]:
import torch as t
x = t.rand(5,3)
print(x)

tensor([[0.8712, 0.8759, 0.1305],
        [0.4280, 0.6167, 0.4285],
        [0.7824, 0.1926, 0.4244],
        [0.1779, 0.8350, 0.3034],
        [0.0027, 0.9952, 0.5967]])


## Tensors （张量）

In [20]:
x = torch.empty(5,3)  # 构造5*3矩阵，不初始化
print(x)

tensor([[-7.4335e-06,  4.5657e-41,  1.2062e-29],
        [ 3.0618e-41,  4.4842e-44,  0.0000e+00],
        [ 8.9683e-44,  0.0000e+00,  1.2062e-29],
        [ 3.0618e-41,  2.8026e-45,  0.0000e+00],
        [ 3.1284e-01,  6.7261e-01,  3.3645e-01]])


In [21]:
# 构造一个随机初始化的矩阵
y = torch.rand(5,3)
print(y)

tensor([[0.7999, 0.4112, 0.9742],
        [0.8955, 0.4649, 0.8637],
        [0.4947, 0.5013, 0.9111],
        [0.1936, 0.3278, 0.1313],
        [0.0374, 0.5952, 0.2076]])


In [22]:
# 构造一个矩阵全为0，而且数据类型为long
z = torch.zeros(5,3,dtype=torch.long)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [23]:
#构造一个张量，直接使用数据：
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [24]:
# 创建一个tensor基于已经存在的tensor
x = x.new_ones(5,3,dtype=torch.double)
# new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [25]:
x = torch.randn_like(x,dtype=torch.float)
# override dtype
print(x)

tensor([[-0.0539, -0.2203,  0.7099],
        [ 1.1625,  1.9467, -0.3588],
        [ 0.4095, -1.2473,  0.1137],
        [-1.9670,  1.4106,  0.6605],
        [-0.0432,  1.7408, -1.1597]])


In [26]:
# 获取维度信息
print(x.size())

torch.Size([5, 3])


加法   方式一

In [27]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 0.0600,  0.2275,  0.8490],
        [ 1.9464,  2.4704, -0.0391],
        [ 1.0775, -0.8741,  0.8369],
        [-1.8151,  1.8332,  1.3434],
        [ 0.4661,  1.8308, -0.7238]])


加法  方式二

In [28]:
print(torch.add(x,y))

tensor([[ 0.0600,  0.2275,  0.8490],
        [ 1.9464,  2.4704, -0.0391],
        [ 1.0775, -0.8741,  0.8369],
        [-1.8151,  1.8332,  1.3434],
        [ 0.4661,  1.8308, -0.7238]])


加法：提供一个输出tensor作为参数

In [29]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 0.0600,  0.2275,  0.8490],
        [ 1.9464,  2.4704, -0.0391],
        [ 1.0775, -0.8741,  0.8369],
        [-1.8151,  1.8332,  1.3434],
        [ 0.4661,  1.8308, -0.7238]])


加法：in-place

In [30]:
y.add_(x)
print(y)

tensor([[ 0.0600,  0.2275,  0.8490],
        [ 1.9464,  2.4704, -0.0391],
        [ 1.0775, -0.8741,  0.8369],
        [-1.8151,  1.8332,  1.3434],
        [ 0.4661,  1.8308, -0.7238]])
